# testing all notebooks
name: Testing notebooks

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11', '3.12']
        notebook: [ Ch02-statlearn-lab.ipynb,
                    Ch03-linreg-lab.ipynb,
                    Ch04-classification-lab.ipynb,
                    Ch05-resample-lab.ipynb,
                    Ch06-varselect-lab.ipynb,
                    Ch07-nonlin-lab.ipynb,
                    Ch08-baggboost-lab.ipynb,
                    Ch09-svm-lab.ipynb,
                    Ch10-deeplearning-lab.ipynb,
                    Ch11-surv-lab.ipynb,
                    Ch12-unsup-lab.ipynb,
                    Ch13-multiple-lab.ipynb]
        exclude:
          - python-version: '3.11'
            notebook: Ch10-deeplearning-lab.ipynb

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.15"


    - name: Set up Python
      shell: bash
      run: |
        uv python install ${{ matrix.python-version }}

    - name: Create venv
      shell: bash
      run: uv venv

    - name: Install requirements
      shell: bash
      run: |
        uv pip install --upgrade pip
        uv pip install -r requirements.txt
        uv pip install pytest nbmake

    - name: Create test configs
      shell: bash
      run: |
          echo "# Hello nbmake" > conftest.py
          cat >> conftest.py << 'EOF'
          import warnings
          import pytest
          import sys

          def pytest_configure(config):
              warnings.filterwarnings('error', category=FutureWarning)
              warnings.filterwarnings('error', category=DeprecationWarning)
              warnings.filterwarnings('error', category=UserWarning)
              warnings.simplefilter('always')
              # Force warnings to be displayed even if they've been displayed before
              warnings.simplefilter('always', FutureWarning)
              
          @pytest.fixture(autouse=True)
          def configure_warnings():
              with warnings.catch_warnings(record=True) as w:
                  warnings.simplefilter("always")
                  # Ensure all warnings are turned into errors
                  warnings.filterwarnings('error')
                  yield w

          def pytest_runtest_call(item):
              warnings.simplefilter("error")
          EOF

          echo "[pytest]" > pytest.ini
          echo "filterwarnings =" >> pytest.ini
          echo "    error" >> pytest.ini
          echo "    always::FutureWarning" >> pytest.ini

    - name: Test
      shell: bash
      run: |
        PYTHONWARNINGS=always uv run pytest --nbmake --nbmake-timeout=3600 ${{ matrix.notebook }}
